// <auto-generated />
using System;
using FamilyFinance.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFinance.Persistence.Migrations
{
    [DbContext(typeof(FFDbContext))]
    [Migration("20221207150816_InitForAzure")]
    partial class InitForAzure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetType")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BudgetItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetType = 0,
                            Item = "Salary"
                        },
                        new
                        {
                            Id = 2,
                            BudgetType = 0,
                            Item = "Deposit interest"
                        },
                        new
                        {
                            Id = 3,
                            BudgetType = 0,
                            Item = "Financial aid"
                        },
                        new
                        {
                            Id = 4,
                            BudgetType = 1,
                            Item = "Insurance"
                        },
                        new
                        {
                            Id = 5,
                            BudgetType = 1,
                            Item = "Products"
                        },
                        new
                        {
                            Id = 6,
                            BudgetType = 1,
                            Item = "Clothes"
                        },
                        new
                        {
                            Id = 7,
                            BudgetType = 1,
                            Item = "Communal payments"
                        },
                        new
                        {
                            Id = 8,
                            BudgetType = 1,
                            Item = "Rent"
                        },
                        new
                        {
                            Id = 9,
                            BudgetType = 1,
                            Item = "Medicine"
                        },
                        new
                        {
                            Id = 10,
                            BudgetType = 1,
                            Item = "Auto"
                        },
                        new
                        {
                            Id = 11,
                            BudgetType = 1,
                            Item = "Kindergarten/School"
                        },
                        new
                        {
                            Id = 12,
                            BudgetType = 1,
                            Item = "Presents"
                        },
                        new
                        {
                            Id = 13,
                            BudgetType = 1,
                            Item = "Travel, vacation"
                        },
                        new
                        {
                            Id = 14,
                            BudgetType = 1,
                            Item = "Emergency expenses"
                        },
                        new
                        {
                            Id = 15,
                            BudgetType = 1,
                            Item = "Taxes"
                        },
                        new
                        {
                            Id = 16,
                            BudgetType = 1,
                            Item = "Education"
                        },
                        new
                        {
                            Id = 17,
                            BudgetType = 1,
                            Item = "Loan payment"
                        },
                        new
                        {
                            Id = 18,
                            BudgetType = 1,
                            Item = "Entertainment"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.FinancialOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinOperation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinancialOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinOperation = "Credit"
                        },
                        new
                        {
                            Id = 2,
                            FinOperation = "Deposit"
                        },
                        new
                        {
                            Id = 3,
                            FinOperation = "Payment by instalments"
                        },
                        new
                        {
                            Id = 4,
                            FinOperation = "Real estate investment"
                        },
                        new
                        {
                            Id = 5,
                            FinOperation = "Investments in securities"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.UserOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinOperationId")
                        .HasColumnType("int");

                    b.Property<int>("SumBudgetItem")
                        .HasColumnType("int");

                    b.Property<int>("SumFinOperation")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetItemId");

                    b.HasIndex("FinOperationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetItemId = 1,
                            Date = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 50000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BudgetItemId = 1,
                            Date = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 50000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BudgetItemId = 1,
                            Date = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BudgetItemId = 7,
                            Date = new DateTime(2022, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            BudgetItemId = 7,
                            Date = new DateTime(2022, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            BudgetItemId = 7,
                            Date = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinOperationId = 2,
                            SumBudgetItem = 0,
                            SumFinOperation = 30000,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Peter",
                            LastName = "Parker",
                            PasswordHash = new byte[] { 37, 14, 215, 175, 15, 20, 124, 179, 242, 171, 29, 249, 17, 124, 131, 31, 91, 138, 166, 33, 72, 124, 188, 238, 235, 150, 148, 216, 86, 146, 216, 26, 139, 59, 30, 150, 6, 134, 93, 237, 36, 99, 151, 203, 46, 156, 212, 100, 203, 241, 31, 151, 161, 190, 201, 208, 50, 127, 112, 59, 239, 46, 77, 68 },
                            PasswordSalt = new byte[] { 30, 146, 6, 56, 145, 254, 37, 161, 200, 173, 96, 198, 107, 156, 73, 166, 185, 140, 164, 96, 147, 50, 180, 96, 105, 88, 75, 100, 167, 173, 40, 147, 220, 154, 135, 188, 238, 239, 188, 4, 244, 49, 34, 72, 254, 151, 248, 43, 31, 16, 44, 60, 12, 116, 77, 122, 141, 207, 110, 135, 193, 61, 155, 216, 109, 103, 102, 12, 196, 172, 0, 34, 145, 117, 176, 35, 116, 64, 180, 236, 7, 77, 89, 137, 34, 10, 43, 153, 185, 106, 60, 105, 29, 28, 108, 11, 125, 126, 21, 77, 159, 29, 194, 112, 24, 225, 27, 119, 177, 218, 146, 103, 136, 149, 125, 227, 141, 137, 243, 75, 136, 64, 178, 62, 50, 63, 18, 238 },
                            UserName = "peter_parker"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Wanda",
                            LastName = "Maximoff",
                            PasswordHash = new byte[] { 3, 164, 22, 106, 226, 245, 198, 10, 118, 160, 127, 121, 250, 205, 64, 226, 224, 78, 37, 247, 42, 109, 135, 93, 18, 91, 218, 234, 150, 60, 192, 56, 169, 153, 170, 252, 189, 144, 4, 18, 205, 189, 196, 89, 75, 193, 86, 126, 49, 51, 103, 78, 81, 59, 197, 42, 158, 54, 156, 217, 74, 45, 196, 16 },
                            PasswordSalt = new byte[] { 30, 146, 6, 56, 145, 254, 37, 161, 200, 173, 96, 198, 107, 156, 73, 166, 185, 140, 164, 96, 147, 50, 180, 96, 105, 88, 75, 100, 167, 173, 40, 147, 220, 154, 135, 188, 238, 239, 188, 4, 244, 49, 34, 72, 254, 151, 248, 43, 31, 16, 44, 60, 12, 116, 77, 122, 141, 207, 110, 135, 193, 61, 155, 216, 109, 103, 102, 12, 196, 172, 0, 34, 145, 117, 176, 35, 116, 64, 180, 236, 7, 77, 89, 137, 34, 10, 43, 153, 185, 106, 60, 105, 29, 28, 108, 11, 125, 126, 21, 77, 159, 29, 194, 112, 24, 225, 27, 119, 177, 218, 146, 103, 136, 149, 125, 227, 141, 137, 243, 75, 136, 64, 178, 62, 50, 63, 18, 238 },
                            UserName = "wanda_maximoff"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.UserOperation", b =>
                {
                    b.HasOne("FamilyFinance.Domain.Entities.Budget.BudgetItem", "BudgetItem")
                        .WithMany()
                        .HasForeignKey("BudgetItemId");

                    b.HasOne("FamilyFinance.Domain.Entities.Budget.FinancialOperation", "FinOperation")
                        .WithMany()
                        .HasForeignKey("FinOperationId");

                    b.HasOne("FamilyFinance.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetItem");

                    b.Navigation("FinOperation");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
