// <auto-generated />
using System;
using FamilyFinance.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFinance.Persistence.Migrations
{
    [DbContext(typeof(FFDbContext))]
    [Migration("20221115155615_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetType")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BudgetItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetType = 0,
                            Item = "Salary"
                        },
                        new
                        {
                            Id = 2,
                            BudgetType = 0,
                            Item = "Deposit interest"
                        },
                        new
                        {
                            Id = 3,
                            BudgetType = 0,
                            Item = "Financial aid"
                        },
                        new
                        {
                            Id = 4,
                            BudgetType = 1,
                            Item = "Insurance"
                        },
                        new
                        {
                            Id = 5,
                            BudgetType = 1,
                            Item = "Products"
                        },
                        new
                        {
                            Id = 6,
                            BudgetType = 1,
                            Item = "Clothes"
                        },
                        new
                        {
                            Id = 7,
                            BudgetType = 1,
                            Item = "Communal payments"
                        },
                        new
                        {
                            Id = 8,
                            BudgetType = 1,
                            Item = "Rent"
                        },
                        new
                        {
                            Id = 9,
                            BudgetType = 1,
                            Item = "Medicine"
                        },
                        new
                        {
                            Id = 10,
                            BudgetType = 1,
                            Item = "Auto"
                        },
                        new
                        {
                            Id = 11,
                            BudgetType = 1,
                            Item = "Kindergarten/School"
                        },
                        new
                        {
                            Id = 12,
                            BudgetType = 1,
                            Item = "Presents"
                        },
                        new
                        {
                            Id = 13,
                            BudgetType = 1,
                            Item = "Travel, vacation"
                        },
                        new
                        {
                            Id = 14,
                            BudgetType = 1,
                            Item = "Emergency expenses"
                        },
                        new
                        {
                            Id = 15,
                            BudgetType = 1,
                            Item = "Taxes"
                        },
                        new
                        {
                            Id = 16,
                            BudgetType = 1,
                            Item = "Education"
                        },
                        new
                        {
                            Id = 17,
                            BudgetType = 1,
                            Item = "Loan payment"
                        },
                        new
                        {
                            Id = 18,
                            BudgetType = 1,
                            Item = "Entertainment"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.FinancialOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinOperation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinancialOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinOperation = "Credit"
                        },
                        new
                        {
                            Id = 2,
                            FinOperation = "Deposit"
                        },
                        new
                        {
                            Id = 3,
                            FinOperation = "Payment by instalments"
                        },
                        new
                        {
                            Id = 4,
                            FinOperation = "Real estate investment"
                        },
                        new
                        {
                            Id = 5,
                            FinOperation = "Investments in securities"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.UserOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinOperationId")
                        .HasColumnType("int");

                    b.Property<int>("SumBudgetItem")
                        .HasColumnType("int");

                    b.Property<int>("SumFinOperation")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetItemId");

                    b.HasIndex("FinOperationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetItemId = 1,
                            Date = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 50000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BudgetItemId = 1,
                            Date = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 50000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BudgetItemId = 1,
                            Date = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BudgetItemId = 7,
                            Date = new DateTime(2022, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            BudgetItemId = 7,
                            Date = new DateTime(2022, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            BudgetItemId = 7,
                            Date = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SumBudgetItem = 2000,
                            SumFinOperation = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinOperationId = 2,
                            SumBudgetItem = 0,
                            SumFinOperation = 30000,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Peter",
                            LastName = "Parker",
                            PasswordHash = new byte[] { 181, 197, 157, 35, 54, 147, 235, 37, 79, 30, 177, 87, 33, 51, 31, 223, 124, 185, 195, 167, 232, 202, 153, 152, 234, 63, 19, 47, 133, 216, 34, 65, 236, 48, 227, 140, 99, 199, 39, 230, 204, 64, 108, 48, 33, 123, 7, 208, 142, 195, 230, 80, 209, 200, 225, 15, 146, 10, 111, 12, 42, 144, 62, 65 },
                            PasswordSalt = new byte[] { 54, 233, 250, 249, 178, 156, 111, 210, 247, 193, 25, 81, 239, 36, 104, 88, 69, 76, 93, 242, 17, 205, 6, 178, 217, 191, 49, 15, 177, 29, 20, 56, 197, 134, 69, 29, 159, 0, 230, 192, 120, 234, 214, 51, 125, 195, 87, 140, 59, 108, 173, 81, 207, 247, 57, 77, 192, 48, 199, 199, 24, 244, 74, 187, 230, 248, 142, 246, 89, 49, 144, 45, 244, 223, 129, 36, 113, 234, 19, 202, 148, 161, 76, 126, 173, 240, 248, 78, 48, 143, 71, 78, 234, 18, 228, 165, 148, 134, 64, 76, 112, 210, 167, 34, 70, 152, 131, 115, 183, 212, 126, 144, 160, 54, 182, 247, 112, 212, 148, 115, 144, 154, 243, 106, 232, 118, 16, 250 },
                            UserName = "peter_parker"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Wanda",
                            LastName = "Maximoff",
                            PasswordHash = new byte[] { 65, 83, 178, 29, 3, 167, 215, 69, 70, 168, 162, 200, 44, 160, 104, 216, 211, 247, 159, 97, 138, 119, 101, 226, 95, 87, 201, 112, 105, 95, 11, 136, 41, 181, 194, 248, 244, 227, 5, 227, 152, 81, 115, 19, 140, 10, 129, 227, 157, 27, 163, 163, 214, 194, 193, 231, 158, 6, 1, 139, 106, 88, 135, 121 },
                            PasswordSalt = new byte[] { 54, 233, 250, 249, 178, 156, 111, 210, 247, 193, 25, 81, 239, 36, 104, 88, 69, 76, 93, 242, 17, 205, 6, 178, 217, 191, 49, 15, 177, 29, 20, 56, 197, 134, 69, 29, 159, 0, 230, 192, 120, 234, 214, 51, 125, 195, 87, 140, 59, 108, 173, 81, 207, 247, 57, 77, 192, 48, 199, 199, 24, 244, 74, 187, 230, 248, 142, 246, 89, 49, 144, 45, 244, 223, 129, 36, 113, 234, 19, 202, 148, 161, 76, 126, 173, 240, 248, 78, 48, 143, 71, 78, 234, 18, 228, 165, 148, 134, 64, 76, 112, 210, 167, 34, 70, 152, 131, 115, 183, 212, 126, 144, 160, 54, 182, 247, 112, 212, 148, 115, 144, 154, 243, 106, 232, 118, 16, 250 },
                            UserName = "wanda_maximoff"
                        });
                });

            modelBuilder.Entity("FamilyFinance.Domain.Entities.Budget.UserOperation", b =>
                {
                    b.HasOne("FamilyFinance.Domain.Entities.Budget.BudgetItem", "BudgetItem")
                        .WithMany()
                        .HasForeignKey("BudgetItemId");

                    b.HasOne("FamilyFinance.Domain.Entities.Budget.FinancialOperation", "FinOperation")
                        .WithMany()
                        .HasForeignKey("FinOperationId");

                    b.HasOne("FamilyFinance.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetItem");

                    b.Navigation("FinOperation");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
